test cli

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,3 +47,84 @@ jobs:
       # Prettier verification
       - name: "Code formatting verification with Prettier"
         run: npm run prettier:verify
+
+  scratch-org-test:
+    runs-on: ubuntu-latest
+    needs: format-lint-lwc-tests
+    # if: ${{ github.actor != 'dependabot[bot]' }}
+    steps:
+      # Checkout the source code
+      - name: "Checkout source code"
+        uses: actions/checkout@v2
+
+      # Run PMD scan
+      # - name: 'Run PMD scan'
+      #   uses: pmd/pmd-github-action@v1.2.1
+      #   id: pmd
+      #   with:
+      #       sourcePath: 'force-app'
+      #       rulesets: 'ruleset.xml'
+
+      # Check for PMD violations
+      # - name: 'Check for PMD violations'
+      #   if: steps.pmd.outputs.violations != 0
+      #   run: exit 1
+
+      # Install Salesforce CLI
+      - name: "Install Salesforce CLI"
+        run: |
+          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+          mkdir ~/sfdx
+          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+          ~/sfdx/bin/sfdx version
+
+      # Store secret for dev hub
+      - name: "Populate auth file with DEVHUB_SFDX_URL secret"
+        shell: bash
+        run: |
+          echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+          secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+          if [ $secretFileSize == 1 ]; then
+              echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+              exit 1;
+          fi
+
+      # Authenticate dev hub
+      - name: "Authenticate Dev Hub"
+        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+
+      # Create scratch org
+      - name: "Create scratch org"
+        run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+
+      # Deploy source to scratch org
+      - name: "Push source to scratch org"
+        run: sfdx force:source:push
+
+      # Assign permissionset
+      # - name: 'Assign permissionset to default user'
+      #   run: sfdx force:user:permset:assign -n recipes
+
+      # Import sample data
+      # - name: 'Import sample data'
+      #   run: sfdx force:data:tree:import -p ./data/data-plan.json
+
+      # Run Apex tests in scratch org
+      - name: "Run Apex tests"
+        run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
+
+      # Delete temporary test file that Codecov is unable to parse
+      # - name: 'Delete coverage file (temporary step)'
+      #   run: rm ./tests/apex/test-result-707*-codecoverage.json
+
+      # # Upload code coverage data
+      # - name: 'Upload code coverage for Apex to Codecov.io'
+      #   uses: codecov/codecov-action@v2.0.2
+      #   with:
+      #       flags: Apex
+
+      # Housekeeping
+      - name: "Delete scratch org"
+        if: always()
+        run: sfdx force:org:delete -p -u scratch-org
